services:
  - type: web
    name: flipkart-product-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: ASTRA_DB_API_ENDPOINT
        sync: false
      - key: ASTRA_DB_APPLICATION_TOKEN
        sync: false
      - key: ASTRA_DB_KEYSPACE
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000

